"use client";

import Link from "next/link";

const SECTIONS = [
  {
    title: "1. Acceptance of terms",
    content: `By accessing or using Pervasively ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service. These terms apply to all users of the Service.`,
  },
  {
    title: "2. Description of service",
    content: `Pervasively is a content generation tool that helps solopreneurs create platform-ready social media posts for Twitter/X, LinkedIn, and Instagram. The Service operates on a credit-based system. Each credit generates a full week of posts across all supported platforms.`,
  },
  {
    title: "3. Accounts and registration",
    content: `You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to provide accurate and complete information during registration and to keep this information up to date. You must be at least 18 years old to use the Service.`,
  },
  {
    title: "4. Credits and payments",
    content: `The Service operates on a prepaid credit system. Credits are purchased in packs and are non-refundable once used. Unused credits do not expire. All payments are processed securely through Paddle. By making a purchase, you agree to Paddle's terms of service and privacy policy. Pervasively reserves the right to modify pricing at any time, with changes taking effect for future purchases only.`,
  },
  {
    title: "5. Acceptable use",
    content: `You agree to use the Service only for lawful purposes and in a manner that does not infringe the rights of others. You must not use the Service to generate content that is defamatory, obscene, abusive, or otherwise objectionable; to impersonate any person or entity; to violate any applicable laws or regulations; or to attempt to gain unauthorized access to any part of the Service.`,
  },
  {
    title: "6. Intellectual property",
    content: `Content generated by the Service using your product information is owned by you. You grant Pervasively a limited license to process your input data solely for the purpose of providing the Service. The Pervasively platform, branding, and underlying technology remain the exclusive property of Pervasively.`,
  },
  {
    title: "7. AI-generated content",
    content: `The Service uses artificial intelligence to generate content. You acknowledge that AI-generated content may occasionally be inaccurate, incomplete, or unsuitable for your purposes. You are solely responsible for reviewing, editing, and approving all content before publishing it. Pervasively is not liable for any consequences arising from the use of AI-generated content.`,
  },
  {
    title: "8. Data and privacy",
    content: `We collect and process only the data necessary to provide the Service, including account information and your product brief. We do not sell your data to third parties, use third-party tracking, or serve advertising. For full details on how we handle your data, please contact us at yalkabovserdar07@gmail.com.`,
  },
  {
    title: "9. Limitation of liability",
    content: `To the maximum extent permitted by applicable law, Pervasively shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising out of or in connection with your use of the Service. The Service is provided on an "as is" and "as available" basis without warranties of any kind.`,
  },
  {
    title: "10. Termination",
    content: `We reserve the right to suspend or terminate your account at our discretion if you violate these Terms and Conditions. Upon termination, your right to use the Service will immediately cease. Any unused credits at the time of termination for policy violations will be forfeited.`,
  },
  {
    title: "11. Changes to terms",
    content: `We may update these Terms and Conditions from time to time. We will notify you of significant changes by updating the date at the top of this page. Continued use of the Service after changes are posted constitutes your acceptance of the updated terms.`,
  },
  {
    title: "12. Governing law",
    content: `These Terms and Conditions are governed by and construed in accordance with applicable international laws. Any disputes arising from these terms shall be resolved through good-faith negotiation. If you have any concerns, please contact us first at yalkabovserdar07@gmail.com.`,
  },
  {
    title: "13. Contact",
    content: `If you have any questions about these Terms and Conditions, please contact us at yalkabovserdar07@gmail.com. We aim to respond within 3 business days.`,
  },
];

export function TermsClient() {
  return (
    <div style={{ minHeight: "100vh", background: "#080D10", fontFamily: "'Inter', -apple-system, sans-serif", color: "#F0F4F5" }}>

      {/* Ambient background */}
      <div style={{ position: "fixed", inset: 0, backgroundImage: "radial-gradient(rgba(25,97,117,0.10) 1px, transparent 1px)", backgroundSize: "24px 24px", pointerEvents: "none", zIndex: 0 }} />
      <div style={{ position: "fixed", top: -180, left: "50%", transform: "translateX(-50%)", width: 900, height: 460, background: "radial-gradient(ellipse at 50% 0%, rgba(25,97,117,0.12) 0%, transparent 68%)", pointerEvents: "none", zIndex: 0 }} />

      {/* Nav */}
      <nav style={{
        position: "sticky", top: 0, zIndex: 100,
        borderBottom: "1px solid rgba(255,255,255,0.05)",
        background: "rgba(8,13,16,0.85)", backdropFilter: "blur(20px)",
        padding: "0 28px", height: 54,
        display: "flex", alignItems: "center", justifyContent: "space-between",
      }}>
        <Link href="/" style={{ display: "flex", alignItems: "center", gap: 9, textDecoration: "none" }}>
          <img src="/pervasively.jpg" alt="Pervasively" style={{ width: 26, height: 26, borderRadius: 7, objectFit: "cover", boxShadow: "0 0 12px rgba(25,97,117,0.35)" }} />
          <span style={{ fontSize: 14, fontWeight: 600, color: "#EDF2F4", letterSpacing: -0.3 }}>Pervasively</span>
        </Link>
        <Link href="/" style={{ fontSize: 12, fontWeight: 500, color: "#3D5A62", textDecoration: "none" }}>
          ← Back to home
        </Link>
      </nav>

      {/* Content */}
      <main style={{ maxWidth: 680, margin: "0 auto", padding: "56px 24px 100px", position: "relative", zIndex: 1 }}>

        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "#196175", marginBottom: 10 }}>Legal</p>
          <h1 style={{ fontSize: 28, fontWeight: 600, letterSpacing: -0.8, color: "#EDF2F4", marginBottom: 12, lineHeight: 1.2 }}>Terms & Conditions</h1>
          <p style={{ fontSize: 13, color: "#3D5A62", lineHeight: 1.6 }}>
            Last updated: April 2026 · These terms govern your use of Pervasively. Please read them carefully before using the Service.
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
          {SECTIONS.map((section, i) => (
            <div key={i} style={{ borderTop: "1px solid rgba(255,255,255,0.05)", padding: "28px 0" }}>
              <h2 style={{ fontSize: 14, fontWeight: 600, color: "#8AABB5", marginBottom: 12, letterSpacing: -0.2 }}>
                {section.title}
              </h2>
              <p style={{ fontSize: 14, color: "#4A6870", lineHeight: 1.75, margin: 0 }}>
                {section.content}
              </p>
            </div>
          ))}
          <div style={{ borderTop: "1px solid rgba(255,255,255,0.05)" }} />
        </div>

        {/* Footer note */}
        <div style={{
          marginTop: 48,
          background: "rgba(12,20,23,0.65)",
          border: "1px solid rgba(255,255,255,0.062)",
          borderRadius: 14,
          padding: "18px 22px",
          display: "flex",
          alignItems: "flex-start",
          gap: 12,
        }}>
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#2AA5C0" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0, marginTop: 1, opacity: 0.7 }}>
            <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
          </svg>
          <p style={{ fontSize: 13, color: "#3D6672", lineHeight: 1.6, margin: 0 }}>
            Questions about the terms?{" "}
            <a href="mailto:yalkabovserdar07@gmail.com" style={{ color: "#2AA5C0", textDecoration: "none", fontWeight: 500 }}>
              yalkabovserdar07@gmail.com
            </a>
          </p>
        </div>

      </main>
    </div>
  );
}